FROM resin/%%RESIN_MACHINE_NAME%%-golang
FROM resin/raspberrypi-golang
ENV INITSYSTEM on
RUN apt-get -q update && apt-get install -yq --no-install-recommends \
    build-essential \
        && apt-get clean && rm -rf /var/lib/apt/lists/*
WORKDIR /go/src/github.com/resin1/
COPY . ./
WORKDIR /go/src/github.com/resin1/src/github.com/17liamnaddell/resin-go-hello-world
RUN go build
RUN ./resin-go-hello-world
